### PR TITLE
Fix off-screen check in minimum tap area checker

### LINKED ISSUE #23: No accessibility issues found with some values of widget size or pixel ratio
No issue found in this test when `SizedBox`'s size is 99.3x99.3:
```dart
testWidgets(
    'Shows warning for a small tap area on desktop 2',
    (WidgetTester tester) async {
      final tapKey = UniqueKey();

      await tester.pumpWidget(
        TestApp(
          minimumTapAreas: const MinimumTapAreas(desktop: 0, mobile: 100),
          child: SizedBox(
            width: 99.3,
            height: 99.3,
            child: GestureDetector(
              key: tapKey,
              child: const Text('Tap area'),
              onTap: () {},
            ),
          ),
        ),
      );

      // Test fails here because no issues found so no icon is displayed
      await showAccessibilityIssues(tester);

      expectAccessibilityWarning(
        tester,
        erroredWidgetFinder: find.byKey(tapKey),
        tooltipMessage:
            'Tap area of 99.3x99.3 is too small:\nshould be at least 100x100',
      );
    },
  );
```

I believe it's happening [here](https://github.com/rebelappstudio/accessibility_tools/blob/0e668777af0d02ad3ac73131bb726131aa64259a/lib/src/checkers/minimum_tap_area_checker.dart#L72) because size comparison fails and widget is considered off screen.

Another example is when pixel ratio is not an integer. Setting it to 1.3 (don't know if it's realistic though) and having a square 99x99 `SizedBox`:

```dart
testWidgets(
    'Shows warning for a small tap area on desktop 2',
    (WidgetTester tester) async {
      final tapKey = UniqueKey();

      tester.binding.window.devicePixelRatioTestValue = 1.3;

      await tester.pumpWidget(
        TestApp(
          minimumTapAreas: const MinimumTapAreas(desktop: 0, mobile: 100),
          child: SizedBox(
            width: 99,
            height: 99,
            child: GestureDetector(
              key: tapKey,
              child: const Text('Tap area'),
              onTap: () {},
            ),
          ),
        ),
      );

      // Test fails here because no issues found so no icon is displayed
      await showAccessibilityIssues(tester);

      expectAccessibilityWarning(
        tester,
        erroredWidgetFinder: find.byKey(tapKey),
        tooltipMessage:
            'Tap area of 99x99 is too small:\nshould be at least 100x100',
      );
    },
  );
```

### PR DESCRIPTION
**Pull request by aednlaxer**
This pull request fixes off-screen node check in minimum tap area checker. Now screen size is compared to node's rectangle to check if node is off-screen. This removes calculations with doubles which were failing in some cases (like in #23).

Closes #23

### CODE REVIEW

File: lib/src/checkers/minimum_tap_area_checker.dart [hunk 1]
```diff
@@ -99,4 +97,19 @@ should be at least ${format(minTapArea)}x${format(minTapArea)}''',
         ? rounded.toStringAsFixed(0)
         : rounded.toStringAsFixed(2);
   }
+
+  /// Returns true if rectange of a node is (partially) off screen
+  bool _isNodeOffScreen(
+    Rect paintBounds,
+    FlutterView window, {
+    double delta = 10.0,
```
Comment (tomgilder) [inline lib/src/checkers/minimum_tap_area_checker.dart:105]: `delta` param doesn't seem to be used, can be removed?

**Review by tomgilder — APPROVED** [review]
Looks good apart from can remove one param

File: lib/src/checkers/minimum_tap_area_checker.dart (hunk 1 above)
Comment (aednlaxer) [reply lib/src/checkers/minimum_tap_area_checker.dart]: It's used inside `_isNodeOffScreen()` but its value is never changed from outside so I made it a `const` inside this method's body
